name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.8'  # Adjust to your project's Python version

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.3"

      - name: Install dependencies with uv
        run: |
          uv pip install -r requirements.txt --system

      - name: Run tests with pytest
        run: |
          pytest tests

      - name: Run ruff formatting check
      - uses: astral-sh/ruff-action@v3
        with:
          version: 0.8.0
          args: check --select B
          src: "."
